kind: Deployment
apiVersion: apps/v1
metadata:
  name: scylla-rootless
  labels:
    app: scylla-rootless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scylla-rootless
  template:
    metadata:
      labels:
        app: scylla-rootless
        deploymentconfig: scylla-rootless
    spec:
      volumes:
        - name: scylla
          emptydir: {}
      containers:
        - name: scylla-rootless
          image: 'srvmsr/scylla-ocp:tagname:3.3.4'
          volumeMounts:
            - name: scylla
              mountPath: /opt/scylladb/scylla/data
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
