kind: Deployment
apiVersion: apps/v1
metadata:
  name: scylla-rootless
  labels:
    app: scylla-rootless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scylla-rootless
  template:
    metadata:
      labels:
        app: scylla-rootless
        deploymentconfig: scylla-rootless
    spec:
      volumes:
        - name: scylla
          emptydir: {}
      containers:
        - name: scylla-rootless
          ports:
            - containerPort: 9042
          image: 'srvmsr/scylla-ocp:4.4.4'
          volumeMounts:
            - name: scylla
              mountPath: /opt/scylladb/scylla/data
          terminationMessagePolicy: File
          imagePullPolicy: Always         
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: scylla
  labels:
    app: scylla-rootless
spec:
  selector:
    app: scylla-rootless
  ports:
    - protocol: TCP
      port: 9042